name: Google Java Formater

on:
  push:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - main
      - develop

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--set-exit-if-changed"
