name: Google Java Formater

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - master
      - main
      - develop

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-reflowing-long-strings --skip-sorting-imports --skip-removing-unused-imports --dry-run --set-exit-if-changed"
