# Example workflow
name: GoogleJavaFormater

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master
      - main

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --dry-run"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --dry-run"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--skip-sorting-imports --replace"
          # Recommended if you use MacOS:
          # githubToken: ${{ secrets.GITHUB_TOKEN }}
